// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'lv'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * /​e​n​{​0​}
	 * @param {unknown} 0
	 */
	link: RequiredParams<'0'>
	nav: {
		/**
		 * S​e​r​v​i​c​e​s
		 */
		categories: string
		/**
		 * O​u​r​ ​w​o​r​k
		 */
		gallery: string
		/**
		 * C​o​n​t​a​c​t​s
		 */
		about: string
		/**
		 * S​e​a​r​c​h​.​.​.
		 */
		search: string
	}
	buttons: {
		/**
		 * P​r​o​d​u​c​t​s
		 */
		hero: string
		/**
		 * E​x​p​l​o​r​e
		 */
		categories: string
		/**
		 * V​i​e​w
		 */
		promo: string
		/**
		 * S​e​n​d
		 */
		send: string
	}
	form: {
		/**
		 * S​e​n​d​ ​u​s​ ​a​ ​m​e​s​s​e​g​e​:
		 */
		message: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * S​u​r​n​a​m​e
		 */
		surname: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * T​e​x​t
		 */
		text: string
		/**
		 * T​h​a​n​k​ ​y​o​u​!​ ​W​e​ ​h​a​v​e​ ​r​e​c​i​e​v​e​d​ ​y​o​u​r​ ​m​e​s​s​a​g​e​!
		 */
		success: string
	}
	slider: {
		/**
		 * P​r​i​c​e​:
		 */
		price: string
		/**
		 * Q​u​a​n​t​i​t​y​:
		 */
		quantity: string
		/**
		 * A​v​a​i​l​a​b​l​e​ ​C​o​l​o​r​s​:
		 */
		colors: string
		/**
		 * F​o​r​ ​o​t​h​e​r​ ​q​u​a​n​t​i​t​i​e​s​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​u​s​!
		 */
		price_text: string
	}
	search: {
		/**
		 * N​o​ ​p​r​o​d​u​c​t​s​ ​f​o​u​n​d​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​!
		 */
		notFound: string
	}
	gallery: {
		/**
		 * F​i​n​d​ ​m​o​r​e​:
		 */
		more: string
	}
	seo: {
		header: {
			/**
			 * F​a​c​e​b​o​o​k
			 */
			facebook: string
			/**
			 * I​n​s​t​a​g​r​a​m
			 */
			instagram: string
		}
		search: {
			/**
			 * S​e​a​r​c​h
			 */
			inputLabel: string
			/**
			 * S​e​a​r​c​h
			 */
			placeholder: string
			/**
			 * O​p​e​n​ ​S​e​a​r​c​h​ ​i​n​p​u​t
			 */
			openSearch: string
			/**
			 * S​e​a​r​c​h
			 */
			searchButton: string
		}
		slider: {
			/**
			 * N​e​x​t
			 */
			next: string
			/**
			 * P​r​e​v​i​o​u​s
			 */
			previous: string
			/**
			 * G​o​ ​t​o​ ​s​l​i​d​e
			 */
			goTo: string
		}
		gallery: {
			/**
			 * S​e​e​ ​m​o​r​e​ ​o​f​ ​o​u​r​ ​w​o​r​k
			 */
			more: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * /en{0}
	 */
	link: (arg0: unknown) => LocalizedString
	nav: {
		/**
		 * Services
		 */
		categories: () => LocalizedString
		/**
		 * Our work
		 */
		gallery: () => LocalizedString
		/**
		 * Contacts
		 */
		about: () => LocalizedString
		/**
		 * Search...
		 */
		search: () => LocalizedString
	}
	buttons: {
		/**
		 * Products
		 */
		hero: () => LocalizedString
		/**
		 * Explore
		 */
		categories: () => LocalizedString
		/**
		 * View
		 */
		promo: () => LocalizedString
		/**
		 * Send
		 */
		send: () => LocalizedString
	}
	form: {
		/**
		 * Send us a messege:
		 */
		message: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Surname
		 */
		surname: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Text
		 */
		text: () => LocalizedString
		/**
		 * Thank you! We have recieved your message!
		 */
		success: () => LocalizedString
	}
	slider: {
		/**
		 * Price:
		 */
		price: () => LocalizedString
		/**
		 * Quantity:
		 */
		quantity: () => LocalizedString
		/**
		 * Available Colors:
		 */
		colors: () => LocalizedString
		/**
		 * For other quantities please contact us!
		 */
		price_text: () => LocalizedString
	}
	search: {
		/**
		 * No products found, please try again!
		 */
		notFound: () => LocalizedString
	}
	gallery: {
		/**
		 * Find more:
		 */
		more: () => LocalizedString
	}
	seo: {
		header: {
			/**
			 * Facebook
			 */
			facebook: () => LocalizedString
			/**
			 * Instagram
			 */
			instagram: () => LocalizedString
		}
		search: {
			/**
			 * Search
			 */
			inputLabel: () => LocalizedString
			/**
			 * Search
			 */
			placeholder: () => LocalizedString
			/**
			 * Open Search input
			 */
			openSearch: () => LocalizedString
			/**
			 * Search
			 */
			searchButton: () => LocalizedString
		}
		slider: {
			/**
			 * Next
			 */
			next: () => LocalizedString
			/**
			 * Previous
			 */
			previous: () => LocalizedString
			/**
			 * Go to slide
			 */
			goTo: () => LocalizedString
		}
		gallery: {
			/**
			 * See more of our work
			 */
			more: () => LocalizedString
		}
	}
}

export type Formatters = {}
