// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'lv'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * /​e​n​{​0​}
	 * @param {unknown} 0
	 */
	link: RequiredParams<'0'>
	nav: {
		/**
		 * S​e​r​v​i​c​e​s
		 */
		categories: string
		/**
		 * G​a​l​l​e​r​y
		 */
		gallery: string
		/**
		 * A​b​o​u​t
		 */
		about: string
		/**
		 * S​e​a​r​c​h​.​.​.
		 */
		search: string
	}
	buttons: {
		/**
		 * P​r​o​d​u​c​t​s
		 */
		hero: string
		/**
		 * M​o​r​e
		 */
		categories: string
		/**
		 * V​i​e​w
		 */
		promo: string
		/**
		 * S​e​n​d
		 */
		send: string
	}
	form: {
		/**
		 * S​e​n​d​ ​u​s​ ​a​ ​m​e​s​s​e​g​e​:
		 */
		message: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * S​u​r​n​a​m​e
		 */
		surname: string
		/**
		 * E​-​m​a​i​l
		 */
		email: string
		/**
		 * T​e​x​t
		 */
		text: string
	}
}

export type TranslationFunctions = {
	/**
	 * /en{0}
	 */
	link: (arg0: unknown) => LocalizedString
	nav: {
		/**
		 * Services
		 */
		categories: () => LocalizedString
		/**
		 * Gallery
		 */
		gallery: () => LocalizedString
		/**
		 * About
		 */
		about: () => LocalizedString
		/**
		 * Search...
		 */
		search: () => LocalizedString
	}
	buttons: {
		/**
		 * Products
		 */
		hero: () => LocalizedString
		/**
		 * More
		 */
		categories: () => LocalizedString
		/**
		 * View
		 */
		promo: () => LocalizedString
		/**
		 * Send
		 */
		send: () => LocalizedString
	}
	form: {
		/**
		 * Send us a messege:
		 */
		message: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Surname
		 */
		surname: () => LocalizedString
		/**
		 * E-mail
		 */
		email: () => LocalizedString
		/**
		 * Text
		 */
		text: () => LocalizedString
	}
}

export type Formatters = {}
